### ISSUE TITLE
`free_value_from_fn`

### ISSUE THREAD

**Issue by droundy** [RazrFalcon/pico-args#1]
I'd love to see a method added like
```
/// Parses a value without a key.
///
/// Uses a specified function for value conversion.
/// Must be used only once for each option.
/// Will return an error, if any flags are left, or if no arguments are left.
pub fn free_value_from_fn<T>(
    &mut self, 
    f: fn(_: &str) -> Result<T, String>
) -> Result<Option<T>, Error> 
```
This would really be a convenience around `free`, but it would allow me to structure my code more nicely.

BTW, I'm thinking of using `pico-args` as part of the basis for a replacement for [ClapMe](https://crates.io/crates/clapme).  ClapMe (obviously) uses clap, but there isn't really a nice way to specify interdependent sets of arguments with clap.  I was going to write my own argument parser from scratch, but gave what's out there one last look and your project looks just about right.  I'll have to generate help myself anyhow, and you basically save me the tedium of writing the actual parsing code, letting me get to the bits that will slow down the compile!  :)

Amusingly, waiting for clap to compile is part of what made me want to stop using it.  I love that `pico-args` doesn't do anything that I would need to reimplement! My current gripe is just that I want parsing each of the positional arguments to be identical to other parses.

BTW, another design option would be to implement `From<()>` for `Keys`, which would indicate a positional argument.  That would be even nicer for me, but only by a teeny tiny bit, and I can see why you might not like that as an API design, since it would mean that the order of calling the `value_from...` functions would impact the semantics, which is a bit ugly.

**Comment by RazrFalcon** [comment]
Yes, I think that this is a good idea. But this method must be used only after flags. So it will throw `Error::UnusedArgsLeft` if some args were not processed yet. Does it sound good for you?

`pico-args` is stateless, so I'm not sure how to implement positional args.

**Comment by droundy** [comment]
Yes, that is what I was assuming.  This function is how to implement positional args: you just grab them one at a time in the proper order after processing everything else.
