### ISSUE TITLE
Are the `debug_asserts` important?

### ISSUE THREAD

**Issue by felipesere** [RazrFalcon/pico-args#13]
I'm using pico-args in a tiny binary where I am space-concious, so thank you for creating it ❤️ 

Is there a particular reason you decided to use `debug_asserts` to check that flags start with `-` or `--`? 
My CLI interface looks like `fern fmt here` and it works in release but crashes when I write tests against it.

Alternatively I could add support for having multiple `subcommands`?

I'd be happy to open a PR for it.

**Comment by felipesere** [comment]
Solved it by using subcommand.

**Comment by RazrFalcon** [comment]
Yes, -/-- are mandatory.
