### ISSUE TITLE
Multiple value arguments

### ISSUE THREAD

**Issue by darakian** [RazrFalcon/pico-args#18]
Hey, thanks for the crate. Is it possible to have a multi value argument in pico args? ex.
```
./some.bin -f one two three
```
I've tried using `args.values_from_str(["-f", "--flag"]).unwrap_or(vec![]),` with a corresponding struct having a value for flag set to `Vec<String>` but this ends up giving me a vec with just the string `one`. I've also looked around the docs and it's unclear to me if this is possible or not.

**Comment by RazrFalcon** [comment]
No. Only like this: `./some.bin -f 'one two three'`

And I'm not sure that it's possible to implement this without knowing all the commands before-hand, which we don't.

**Comment by darakian** [comment]
Gotcha. Thanks! :)
