### ISSUE TITLE
[Docs] Add a quick Usage section in the Readme

### ISSUE THREAD

**Issue by batisteo** [RazrFalcon/pico-args#3]
It’s always nice to have a little code example of how to use a project on a basic level, to make an idea how Spartan it is.

**Comment by RazrFalcon** [comment]
There is [examples/app.rs](https://github.com/RazrFalcon/pico-args/blob/master/examples/app.rs) and as you can see, it's too long for a readme.

I will think about how to make it more compact.

**Comment by batisteo** [comment]
Having a full code example in less than 40 loc is great! I think it’s perfectly fine to have it in the Readme as is.

**Comment by RazrFalcon** [comment]
Done. I hope it will clarify the usage a bit.
