### ISSUE TITLE
option aliases or additional short or long forms?

### ISSUE THREAD

**Issue by pwFoo** [RazrFalcon/pico-args#32]
Hi @RazrFalcon ,

pico_args works fine with 2 options (short and long or two long options), but can't work with additional options / aliases?

Typical is one short and one long form.
```
force: args.contains(["-f", "--force"]),
```

Two long forms also compile wihout error.
```
force: args.contains(["--force", "--sudo"]),
```

But how to add additional "aliases" for options or subcommands like
```
shutdown: args.contains(["--shutdown", "--poweroff", "-s", "-p"]),
```

1. Is it possible to add more than 2 options?
2. I'm new with rust so maybe a stupid question... Is it possible to generate an subcommand alias? For example `poweroff` should be the same than `shutdown`?
 ```
        Some("poweroff") => {                                      // additional subcommand alias should be "shutdown"...
            Ok(AppArgs::SubcPoweroff {                             
                force: args.contains(["-f", "--force"]),
            })                                                   
        } 
 ```

**Comment by RazrFalcon** [comment]
No, this is not possible and will not be implemented. You should use `clap` or any other more high-level library.

>Is it possible to generate an subcommand alias?

`Some("poweroff") | Some("shutdown") => { ` ?

**Comment by pwFoo** [comment]
Thanks, should work for me.
