### ISSUE TITLE
Combined flags question

### ISSUE THREAD

**Issue by alexwennerberg** [RazrFalcon/pico-args#34]
Hey I had a question about combined flags -- is this something that you don't want to support because of the minimalist principles of this library, or just something that you haven't implemented, but would be open to?

**Comment by RazrFalcon** [comment]
You mean `-abc`? I personally hate them, but I don't mind if someone would write support for them. Behind the feature flag, obviously. 
Also, I don't think it's that easy to implement.

**Comment by alexwennerberg** [comment]
I'll see if I can figure something out if I have a chance.
