### ISSUE TITLE
 method links broken 

### ISSUE THREAD

**Issue by 89z** [RazrFalcon/pico-args#37]
If I go to this page:

https://docs.rs/pico-args/latest/pico_args/struct.Arguments.html

I see a method on the left called `finish`, but if I click it, it doesnt do anything:

https://docs.rs/pico-args/latest/pico_args/struct.Arguments.html#method.finish

**Comment by ahkrr** [comment]
I think this is not an issue of pico-args but of the documentation generation.
If you click on the little plus next to
```
Implementations
[+}  impl Arguments
```
the methods will become visible. 
They were previously there but not visible because of folding.

**Comment by 89z** [comment]
I wonder why other crates are not folded:

https://docs.rs/getopts/latest/getopts/struct.Options.html

**Comment by ahkrr** [comment]
Maybe some default setting for the doc generation changed?
[https://docs.rs/tracing/0.1.26/tracing/instrument/struct.Instrumented.html](https://docs.rs/tracing/0.1.26/tracing/instrument/struct.Instrumented.html)
This is also folded.

**Comment by RazrFalcon** [comment]
I think this is just docs.rs bug.
