### ISSUE TITLE
Repeated args

### ISSUE THREAD

**Issue by jneem** [RazrFalcon/pico-args#38]
I want to support repeated `-v` arguments, where more copies of that argument implies more verbose output. This code works:
```rust
while args.contains("-v") {
    verbosity += 1;
}
```
But I was concerned by the part of the docs where it says that `contains` may only be called once for each flag. Is this behavior intended, and if so would you accept a docs PR to clarify it?

**Comment by RazrFalcon** [comment]
Yes, it become possible lately #35. Docs should indeed be updated. PR is welcome.
