### ISSUE TITLE
non-'static keys

### ISSUE THREAD

**Issue by droundy** [RazrFalcon/pico-args#4]
I'd like to be able to have keys that are not `&'static`, since I'll have to compute some keys at runtime in order to avoid a theoretical combinatoric explosion.  I could do this by simply leaking memory (and it's not much), but is it really so expensive to use `to_string()` in the error cases? Or is there some other reason why you require keys to be `&'static str`?

**Comment by RazrFalcon** [comment]
`'static` is used to simply the code. Why do you need runtime arguments?

**Comment by droundy** [comment]
Basically because users can define a structure that represents a set of arguments, but that structure may be included in another structure, which may need to modify the flags.

See for example:

https://docs.rs/clapme/0.1.15/clapme/guide/index.html#nesting-types

In order for the code for handling vectors in this example to be distinct from the other struct, we need non-static keys. It's a nuisance, but it gains a lot in usability when there are reused types.  Another example would be an IP address, where you want to define the "IP address flags" just once, but might want to have a program with several IP addresses specified.

**Comment by droundy** [comment]
It's possible that the match between pico-args and my (new) crate just isn't as good as it seemed at first.

**Comment by RazrFalcon** [comment]
I still don't understand. Keys are predefined values. You do not generate them before application starts.

**Comment by droundy** [comment]
There question is which code knows the keys. In my case this information is split between two derived implementations that have no way to know what the other part of the key is.

**Comment by RazrFalcon** [comment]
The key is a static, hardcoded string. I'm not sure why it shouldn't be.

Can you provide a concrete example?

**Comment by droundy** [comment]
Imagine an interface where you want to input two vectors, position and velocity.  This you have six flags:. `--position-x`, `--position-y`, `--position-z`, `--velocity-x`, `--velocity-y`, `--velocity-z`.  You might want to write a function to handle any vector, which would add the `-x`, `-y` etc to its argument, and construct the three flags needed for any vector.  Even more so if you wanted to allow input on other coordinate systems, say spherical or cylindrical.  But sounds so would mean that your flags are not `&'static str`.

**Comment by RazrFalcon** [comment]
I still think that this is unnecessary, but I've added it anyway.

**Comment by droundy** [comment]
Feel free to revert. In the meantime I've dropped use of pico-args, which turned out to significantly simplify my code.

**Comment by amhndu** [comment]
Why was this reverted? It would be really helpful to be able to build argument keys at runtime based on some code instead of hard-coding it.
As an example, I'm using enums that are keys to some config map.
```rs
enum ConfigEnum {
    Foo,
    Bar,
    ...
}
```
And I want to configure them like `--foo=42`, I don't want to repeat the key name as both a string and an identifier. It would be trivial to do this if pico supported non-'static string by using `format!("--{}", config_key`

**Comment by RazrFalcon** [comment]
@amhndu Then pico-args is not for you.
