### ISSUE TITLE
docs how to test parse_args()

### ISSUE THREAD

**Issue by tinsel-grumble** [RazrFalcon/pico-args#41]
when look at example using parse_args() how to test? how to test and say unwrap_or() work or -h exit right? i try someth in mod test but no luck

**Comment by RazrFalcon** [comment]
https://github.com/RazrFalcon/pico-args/blob/master/tests/tests.rs ?

**Comment by tinsel-grumble** [comment]
like https://github.com/RazrFalcon/pico-args/blob/master/examples/app.rs how to do test_parse_args or only way test one by one?

**Comment by RazrFalcon** [comment]
I'm sorry, but I do not understand the question.

**Comment by tinsel-grumble** [comment]
how to make unit test for parse_args function in example from the repo? or just do your way and test separate args

**Comment by RazrFalcon** [comment]
The `parse_args` function doesn't have any logic that should be tested. If you really want to, you simply have to manually pass args into it. Like so:

```rust
fn parse_args(args: Vec<std::ffi::OsString>) -> Result<AppArgs, pico_args::Error> {
    let mut pargs = pico_args::Arguments::from_vec();
    // other stuff
}

#[cfg(test)]
mod tests {
    fn to_vec(args: &[&str]) -> Vec<OsString> {
        args.iter().map(|s| s.to_string().into()).collect()
    }

    #[test]
    fn test() {
        let args = super::parse_args(to_vec(&["--version"]));
        // asserts...
    }
}
```

**Comment by tinsel-grumble** [comment]
thx
