### ISSUE TITLE
Measure incremental build time

### ISSUE THREAD

**Issue by martin-t** [RazrFalcon/pico-args#42]
The readme says that build time is measured after `cargo clean`. It's much more common to want fast *incremental* build times to iterate faster (especially in gamedev but most projects would benefit from optimizing incremental builds).

The easiest way to measure this is to append a newline or comment into main.rs before building (though i get the feeling that editing a function might produce more meaningful results but i am not sure how granular rustc's and LLVM's caching is).

Projects that take incremental builds seriously are also probably already using several improvements such as a nightly rustc, `-Zshare-generics=y` and either lld or mold linter - an example config is [here](https://github.com/bevyengine/bevy/blob/main/.cargo/config_fast_builds). This is pretty significant and can reduce incremental builds for example from 12 s to 2 s. It might be interesting to do the comparison using this config for a more convincing argument why pico-args is the best choice.

**Comment by martin-t** [comment]
Clap seems to add a couple hundred ms, and sometimes over a second, so if pico-args doesn't, that would be a good selling point. But it seems very variable depending on what code was changed - i haven't measured it properly.

I understand your position. Currently i am more or less happy with manual parsing. I'd measure it properly if i was considering pico-args more seriously - maybe when my parsing gets too complex but not in the near future.

**Comment by RazrFalcon** [comment]
pico-args is less than 1000 LOC, it cannot possibly be slow. By design.

We cannot sell something we cannot measure.
