### ISSUE TITLE
Confusing Display output for *ArgumentParsingFailed errors

### ISSUE THREAD

**Issue by glts** [RazrFalcon/pico-args#43]
When `Error::Utf8ArgumentParsingFailed` and `Error::ArgumentParsingFailed` are printed via `Display` the result looks something like this:

```
failed to parse '5.4' cause invalid IP address
failed to parse a binary argument cause invalid IP address
```

This wording seems a bit confusing. I’d like to suggest using a colon to separate the two clauses:

```
failed to parse '5.4': invalid IP address
failed to parse a binary argument: invalid IP address
```

**Comment by RazrFalcon** [comment]
Yes, this is a good idea.

**Comment by RazrFalcon** [comment]
Fixed https://github.com/RazrFalcon/pico-args/pull/44
