### ISSUE TITLE
define order in which repeated options are returned

### ISSUE THREAD

**Issue by droundy** [RazrFalcon/pico-args#5]
Currently the code supports repeated options so

./program --input first-input --input second-input

can work just fine, but it returns the second one before the first one.  I'm okay with this behavior (I can reverse them), but would prefer for this to be documented, so I wouldn't find my code breaking due to an implementation change.

**Comment by droundy** [comment]
I'll note that since I push the args onto a `Vec`, the current behavior is actually more convenient, since pushing them automatically reverses them, so I don't need to reverse them again to get them back into order.

**Comment by RazrFalcon** [comment]
>but it returns the second one before the first one

I think that this is a bug in your code. `pico-args` uses linear order.

**Comment by droundy** [comment]
You are correct.  I don't yet understand what's going on in my code, but the order you output flags is from first to last.
