### ISSUE TITLE
Inconsistent docs -- are combined arguments supported?

### ISSUE THREAD

**Issue by maaku** [RazrFalcon/pico-args#60]
The cargo docs for this crate seem to be inconsistent. It first says that combined flags like `-abc` are out of scope, then discusses how to enable combined flags. Which is it?

<img width="865" alt="combined-flags" src="https://github.com/RazrFalcon/pico-args/assets/69154/c7588b9d-fe2a-44cb-b3b6-3637ffe1ff91">

**Comment by RazrFalcon** [comment]
Thanks.
