### ISSUE TITLE
Compile clap with no default features

### ISSUE THREAD

**Issue by CreepySkeleton** [RazrFalcon/pico-args#8]
The comparison is not exactly fair because clap has few optional features enabled by default:

* `vec_map` sacrifices some compile time (one more dependency) and binary bloat for runtime speedup
* `suggestions` enables "did you mean foo?" messages, one more dependency + bloat
* `color` for colorizing help messages, few more dependencies + bloat

Could you please compile clap with `default-features = false`? Although I don't expect incredible improvements, I'm curious how much impact these have on clap.

P.S. The same story with `structopt`

**Comment by RazrFalcon** [comment]
`default-features = false` doesn't did much. 1KiB less size (yes, one) and 0.25s faster compile time. Basically no changes.

**Comment by CreepySkeleton** [comment]
I kind of expected that :)
