### ISSUE TITLE
`cargo test --release` fails

### ISSUE THREAD

**Issue by cuviper** [RazrFalcon/pico-args#9]
While `cargo test` passes for me, `cargo test --release` fails a few tests.

```
failures:

---- invalid_flag_02 stdout ----
note: test did not panic as expected
---- invalid_flag_03 stdout ----
note: test did not panic as expected
---- invalid_flag_04 stdout ----
note: test did not panic as expected

failures:
    invalid_flag_02
    invalid_flag_03
    invalid_flag_04
```

I think this is because the `From` impls use `debug_assert`, which does nothing in release builds. Oddly, `invalid_flag_01` still passed, but using `cargo test -- --nocapture` I can see that it's hitting different asserts in debug/release builds, so it still satisfies `#[should_panic]`.

Note: we test release builds in Fedora so our full rpm build+check all uses the same thing.

**Comment by RazrFalcon** [comment]
This is an expected behavior. You should not run tests in release.

If it's really important to run them in release, I can simply hide them behind `#[cfg(debug_assertions)]`

**Comment by cuviper** [comment]
> I can simply hide them behind `#[cfg(debug_assertions)]`

I think that would better reflect your expected behavior, at least.
